version: '3.8'

services:
  app:
    image: danerbrear/domain_ip_info_handler:latest
    build:
      context: .
      target: prod
    ports:
      - 8083:8083
      - 9229:9229
    environment:
      - SERVER_PORT=8083
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: domain-ip-info-net