version: '3.8'

services:
  app:
    image: danerbrear/reverse-dns:latest
    build: .
    ports:
      - 8081:8081
      - 9229:9229
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./:/app