version: '3.8'

services:
  domain-service:
    image: danerbrear/reverse-dns:latest
    build: 
      context: .
      target: prod
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8082
      - NODE_ENV=prod
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: domain-ip-info-net